spring:
  application:
    name: aidev
  ai:
    openai:
      api-key: <<>>
      embedding:
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: "gpt-4-turbo"
    vectorstore:
      pinecone:
        api-key: <<>>
        index-name: aidevs
        project-id: <<>>
        environment: gcp-starter
        namespace: ""


client:
  openaimoderationapi:
    url: https://api.openai.com/v1
  serpapi:
    apiKey: <<>>
  aidevs:
    url: https://tasks.aidevs.pl
    apiKey: <<>>
  renderform:
    url: https://get.renderform.io/api/v2
    apiKey: <<>>

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

task: md2html

address: <<>>

logging:
  level:
    org:
      eu:
        dabrowski:
          aidev: DEBUG

