spring:
  application:
    name: aidev
  ai:
    openai:
      api-key: <<>>
      embedding:
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: "gpt-4-turbo"
    vectorstore:
      pinecone:
        api-key: <<>>
        index-name: aidevs
        project-id: lslz2wi
        environment: gcp-starter
        namespace: ""


client:
  openaimoderationapi:
    url: https://api.openai.com/v1
  aidevs:
    url: https://tasks.aidevs.pl
    apiKey: <<>>

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

task: ownapi

address: http://<<>>>:8080/
